filter:
    paths: [module/*/src/*]
before_commands:
    - 'composer install --dev --prefer-source'
tools:
    external_code_coverage:
        timeout: 600
    php_mess_detector: true
    php_code_sniffer: true
    sensiolabs_security_checker: true
    php_code_coverage: true
    php_pdepend: true
    php_loc:
        enabled: true
    php_cpd:
        enabled: true
