language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

services:
  - mongodb

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running YAWIK phpunit tests
  - sudo apt-get install -y --force-yes php5-intl php5-curl php5-xsl

  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script: 
  - phpenv config-add .travis/phpenv.ini
  - ./install.sh -b .travis/build.properties.travis
  - ./compser.phar self-update
  - ./composer.phar install

script:
  - phpunit --configuration travis.phpunit.xml
