language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
services:
  - mongodb
before_script: phpenv config-add .travis/phpenv.ini

script:
  - composer install
  - phpunit --configuration travis.phpunit.xml
