language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"

services:
  - mongodb

env:
  - PECLMONGO=mongo-1.5.8

before_install:
  - sudo apt-get update > /dev/null

install:
  # install php packages required for running YAWIK phpunit tests
  - sudo apt-get install -y --force-yes php5-intl php5-curl php5-xsl

  # add composer's global bin directory to the path
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

before_script: 
  - sh -c "wget http://pecl.php.net/get/$PECLMONGO.tgz"
  - sh -c "tar xfz $PECLMONGO.tgz"
  - sh -c "cd $PECLMONGO && phpize && ./configure && make && sudo make install"
  - phpenv config-add .travis/phpenv.ini
  - ./install.sh -b .travis/build.properties.travis
  - ./composer.phar self-update
  - ./composer.phar install

script:
  - ln -s ../test/build/logs build
  - phpunit --configuration $TRAVIS_BUILD_DIR/test/phpunit.xml

after_script:
  - php vendor/bin/coveralls -vvv
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=json-clover build/logs/coveralls-upload.json

